var tableData = [
    [
        {
            "value":"1",
            "formatted_value":"1",
            "style":{
                "bbc":"000000",
                "bbs":"none",
                "bbw":"none",
                "lbc":"000000",
                "lbs":"none",
                "lbw":"none",
                "rbc":"000000",
                "rbs":"none",
                "rbw":"none",
                "tbc":"000000",
                "tbs":"none",
                "tbw":"none",
                "color":"000000",
                "font-family":"Calibri",
                "font-size":"11pt",
                "font-style":"normal",
                "font-weight":"400",
                "height":"20px",
                "text-align":"right",
                "vertical-align":"bottom",
                "white-space":"nowrap",
                "width":"64px",
                "text-wrap":"normal",
                "word-wrap":"normal"
            }
        },
        {
            "value":"2",
            "formatted_value":"2",
            "style":{
                "background-color":"FFFFFF",
                "bbc":"000000",
                "bbs":"none",
                "bbw":"none",
                "lbc":"000000",
                "lbs":"none",
                "lbw":"none",
                "rbc":"000000",
                "rbs":"none",
                "rbw":"none",
                "tbc":"000000",
                "tbs":"none",
                "tbw":"none",
                "color":"000000",
                "font-family":"Calibri",
                "font-size":"11pt",
                "font-style":"normal",
                "height":"20px",
                "text-align":"right",
                "vertical-align":"bottom",
                "white-space":"nowrap",
                "width":"64px",
                "text-wrap":"normal",
                "word-wrap":"normal"
            }
        },
        {
            "value":"3",
            "formatted_value":"3",
            "style":{
                "background-color":"FFFFFF",
                "bbc":"000000",
                "bbs":"none",
                "bbw":"none",
                "lbc":"000000",
                "lbs":"none",
                "lbw":"none",
                "rbc":"000000",
                "rbs":"none",
                "rbw":"none",
                "tbc":"000000",
                "tbs":"none",
                "tbw":"none",
                "color":"000000",
                "font-family":"Calibri",
                "font-size":"11pt",
                "font-style":"normal",
                "font-weight":"400",
                "height":"20px",
                "text-align":"-webkit-right",
                "vertical-align":"bottom",
                "white-space":"nowrap",
                "width":"64px",
                "text-wrap":"normal",
                "word-wrap":"normal"
            }
        }
    ]
];

page.Content.canDoDelta = false;
page.Content.update(tableData, true);
page.push().then(function() {
    console.log('sucesss');
}, (err) => {
   console.log('fail');
});
